# @package _group_
data_root_dir: /home/hmendesp/datasets/places_standard_dataset/
out_root_dir: /home/hmendesp/Workspace/personal-github/lama/experiments/
tb_dir: /home/hmendesp/Workspace/personal-github/lama/tb_logs/
pretrained_models: /home/hmendesp/Workspace/personal-github/lama/
